### ISSUE TITLE
Why this is not a plugin?

### ISSUE THREAD

**Issue by chojnicki** [ikcb/animated-tailwindcss#163]
Like in title.
This package does exactly what I need, and it's great! But I'm confused about installation explained in docs (which are also great btw).

```
const withAnimations = require('animated-tailwindcss');

module.exports = withAnimations({
  // your (existing) Tailwind CSS config here
});
```

It's first time I see some kind of wrapper for whole tailwind. I feel weird about that :P Is there any good reason for that implementation? Cant it be just plugin?

https://tailwindcss.com/docs/plugins

I tried to just add this to `plugins: []` but without success.

**Comment by brc-dd** [comment]
Yeah, I agree that this is not the conventional method to import external stuff in TailwindCSS. I made this a wrapper because I couldn't find any example or documentation on automatically injecting specific keyframes using plugins.

FWIW, another possible implementation was to export animations, keyframes, and utilities separately. Something like this:

```js
const animations = require('animated-tailwindcss/animations');
const keyframes = require('animated-tailwindcss/keyframes');
const animationPlugin = require('animated-tailwindcss/plugin');

module.exports = {
    theme: {
        extend: {
            animation: { ...animations },
            keyframes: { ...keyframes }
        }
    },
    plugins: [animationPlugin]
}
```

But I think the current approach is much easier to get started than this. Also, `withAnimations` is not a wrapper for the whole TailwindCSS; it wraps your config so that the config TailwindCSS gets has all these animations, keyframes, and plugins (basically so you don't need to write the above code yourself). Also, this wrapper approach is quite popular with frameworks like Next.js.
